use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :domoapi_web, DomoapiWeb.Endpoint,
  http: [port: 8001],
  url: [host: "domoapi.sandlabs.ru", port: 8001],
  load_from_system_env: true,
  server: true,
  cache_static_manifest: "priv/static/cache_manifest.json"

config :domoapi_web,
  big_brother_host: System.get_env("BIG_BROTHER_HOST"),
  big_brother_token: System.get_env("BIG_BROTHER_TOKEN")

config :domoapi_web,
  rabbit_host: System.get_env("RABBIT_HOST"),
  rabbit_login: System.get_env("RABBIT_LOGIN"),
  rabbit_password: System.get_env("RABBIT_PASSWORD"),
  rabbit_port: System.get_env("RABBIT_PORT"),
  rabbit_exchange: System.get_env("RABBIT_ECHANGE"),
  rabbit_queue: System.get_env("RABBIT_QUEUE")

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :domoapi_web, DomoapiWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         :inet6,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :domoapi_web, DomoapiWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases (Elixir v1.9+)
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start each relevant endpoint:
#
#     config :domoapi_web, DomoapiWeb.Endpoint, server: true
#
# Then you can assemble a release by calling `mix release`.
# See `mix help release` for more information.
